---
- name: Install required packages for virt_pool module usage
  package:
    name: "{{ item }}"
    state: latest
  with_items: "{{ virtpool_packages }}"

- name: Define Storage Pool for default
  virt_pool:
    command: define
    name: default
    xml: '{{ lookup("template", "roles/node-prep/templates/dir.xml.j2") }}'

- name: Start Storage Pool for default
  virt_pool:
    state: active
    name: default

- name: Autostart Storage Pool for default
  virt_pool:
    autostart: yes
    name: default
