---
- name: Check if Pull Secret is set
  debug:
    msg: "variable 'pullsecret' is not set"
  failed_when: pullsecret is not defined or pullsecret == ""

- name: Generate install-config.yaml
  template: 
    src: install-config.j2
    dest: "{{ dir }}/install-config.yaml"
    owner: "{{ myuser }}"
    group: "{{ myuser }}"
    mode: '0644'
  when: 
  - pullsecret is defined
  - pullsecret != ""

- name: Verify that SSH key for {{ myuser }} exists
  stat:
    path: /home/{{ myuser }}/.ssh/id_rsa.pub
  register: sshkeypath

- name: Get contents of the ssh key for {{ myuser }}
  shell: |
    cat /home/{{ myuser }}/.ssh/id_rsa.pub
  register: sshkeycontents
  when: sshkeypath.stat.exists == true

- name: Copy the ssh key into the install-config.yaml file
  shell: |
    echo "sshKey: '{{ sshkeycontents.stdout }}'" >> {{ dir }}/install-config.yaml

- name: Make a backup of the install-config.yaml file
  copy:
    src: "{{ dir }}/install-config.yaml"
    dest: "{{ dir }}/install-config.yaml.bkup"
    owner: "{{ myuser }}"
    group: "{{ myuser }}"
    mode: '0644'
    remote_src: yes

