---
- name: Add Manifests from files dir
  copy:
    src: "{{ item }}"
    dest: "{{ dir }}/openshift/"
    owner: "{{ myuser }}"
    group: "{{ myuser }}"
  with_fileglob:
    - roles/installer/files/*

